spring.datasource.url=jdbc:mysql://localhost:3306/sseiia
spring.datasource.username=root
spring.datasource.password=2103
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
jwt.expiration = 36000
